
services:
  # frontend:
  #   build: pharma-tech
  #   command: rm -rf /tmp/nitro 
  #   ports:
  #     - "3000:3000"
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tinatina
      POSTGRES_DB: pharmatech
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    

    ports:
      - "5432:5432"
  backend:
    build: Back-end-Pharmatech
    depends_on:
      - postgres
    ports:
      - "3003:3003"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tinatina
      POSTGRES_DB: pharmatech
      DB_HOST: postgres
      DB_PORT: 5432
      DB_CONNECTION_STRING: "postgresql://postgres:tinatina@postgres:5432/pharmatech"
    
  frontend_admin:
    build: pharmatech-nuxt-admin
    depends_on:
      - backend
    ports:
      - "3002:3000"
    environment:
      NUXT_PUBLIC_API_BASE: "https://api.techcare.store/api"
      NUXT_PUBLIC_API_PARENT: "https://api.techcare.store"

  frontend_client:
    build: pharma-tech
    depends_on:
      - backend
    ports:
      - "3001:3001"
    environment:
      NUXT_PUBLIC_API_BASE: "https://api.techcare.store"

volumes:
  pgdata: